version: "3"
services:
  envoy:
    # pre-compiled image:
    #  image: envoyproxy/envoy-dev
    # own image:
    #  build: docker/envoy
    build: docker/envoy
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ".:/input:ro"
    entrypoint: /usr/bin/python3 hot-restarter.py start-envoy.sh
  httpbin:
    build: docker/httpbin
    volumes:
      - ".:/input:ro"
  controlplane:
    build: docker/envoy-control-plane-stub
    ports:
      - "8080:8080"
    volumes:
      - ".:/input:ro"
