apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - name: mariadb
      port: 3306
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      serviceAccountName: mariadb
      containers:
        - name: mariadb
          image: localhost/mariadb:latest
          imagePullPolicy: Never
          env:
            - name: MARIADB_USER
              value: "keycloak"
            - name: MARIADB_PASSWORD
              value: "keycloak"
            - name: MARIADB_ROOT_PASSWORD
              value: "keycloak"
            - name: MARIADB_DATABASE
              value: "keycloak"

          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: mariadb-config
              subPath: my.cnf
              mountPath: /etc/mysql/my.cnf
            - name: mariadb-config
              subPath: keyfile
              mountPath: /etc/mysql/keyfile
      volumes:
        - name: mariadb-config
          configMap:
            name: mariadb-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  my.cnf: |
    [client-server]
    socket = /run/mysqld/mysqld.sock
    !includedir /etc/mysql/mariadb.conf.d/
    !includedir /etc/mysql/conf.d/

    [mariadb]
    #plugin-load-add=file_key_management.so

    # Note that the loose option prefix is specified. This option prefix is used in case the plugin hasn't been installed yet.
    #loose_file_key_management_filename = /etc/mysql/keyfile

    #plugin-load-add=hashicorp_key_management.so

    #hashicorp-key-management-vault-url=openbao:8200/v1/mariadb-keys
    #hashicorp-key-management-token=s.9YpPv04tDBOrX0zlZH48vfS7

    #innodb_encrypt_tables = FORCE
    #innodb_encrypt_log = ON
    #innodb_encrypt_temporary_tables = ON

    #encrypt_tmp_disk_tables = ON
    #encrypt_tmp_files = ON
    #encrypt_binlog = ON
    #aria_encrypt_tables = ON

    #innodb_encryption_threads = 4
    #innodb_encryption_rotation_iops = 2000

  keyfile: |
    1;5a4e67f60192c0291e08344b630d4f1a34d412150bae97b4f2d3f0fae8153cf6
    2;b68c74069204cd87496564de5a386531a238eefe28224db0ee72e78ddedaa98d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5
        ports:
        - containerPort: 80
        env:
#        - name: PMA_PORT
#          value: "3306"
        - name: PMA_HOST
          value: mariadb
        - name: PMA_USER
          value: root
        - name: PMA_PASSWORD
          value: keycloak
#        - name: PMA_ABSOLUTE_URI
#          value: "http://phpmyadmin.127-0-0-121.nip.io/phpmyadmin"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: pgadmin
spec:
  virtualhost:
    fqdn: phpmyadmin.127-0-0-121.nip.io
  routes:
    - services:
        - name: phpmyadmin
          port: 80
