version: "3"
services:
  # OLC configuration for the server is in templates/*
  # Pre-condition to run:
  #   rm -rf certs && mkdir certs && certyaml --destination certs configs/certs.yaml
  openldap:
    build: docker/openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - .:/input:ro
      - ./output:/output
    environment:
      - CERT_FILENAME=/input/certs/ldap.pem
      - KEY_FILENAME=/input/certs/ldap-key.pem
      - CA_FILENAME=/input/certs/client-ca.pem
  ldap-client:
    build: docker/ldap-client
    ports:
      - "2222:22"
    volumes:
      - .:/input:ro

  # postgres requires specific permissions for the certs
  postgres-init:
    image: docker.io/postgres:14-alpine
    entrypoint: sh
    # PEM -> DER conversion for private key is not needed anymore?
    # openssl pkcs8 -topk8 -inform PEM -outform DER -nocrypt -in input/certs/postgres-admin-key.pem -out certs/postgres-admin-key.pem
    command: -x -c "cp -a input/certs/* /certs && chown 70 certs/* && chmod 600 certs/*"
    volumes:
      - .:/input:ro
      - postgres-certs:/certs

  postgres:
    image: docker.io/postgres:14-alpine
    command: -c config_file=/configs/postgres.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - postgres-certs:/certs:ro
      - ./configs:/configs:ro
    depends_on:
      postgres-init:
       condition: service_completed_successfully

volumes:
  postgres-certs:
