# Pre-condition to run:
#     rm -rf certs && mkdir certs && certyaml --destination certs configs/certs.yaml
#
# Start
#     docker-compose up
#
# Cleanup
#     docker-compose down -v
#     docker-compose rm -f -v
#

version: "3.8"
services:
  # OLC configuration for the server is in templates/*
  openldap:
    build: docker/openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - .:/input:ro
      - ./output:/output
    environment:
      - CERT_FILENAME=/input/certs/ldap.pem
      - KEY_FILENAME=/input/certs/ldap-key.pem
      - CA_FILENAME=/input/certs/client-ca.pem

  # sshd with sssd
  #   sshpass -p user ssh user@localhost -p 2222 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "echo Hello world!"
  ldap-client:
    build: docker/ldap-client
    ports:
      - "2222:22"
    volumes:
      - .:/input:ro

  # postgres requires specific permissions for the certs
  postgres-init:
    image: docker.io/postgres:14-alpine
    entrypoint: sh
    command: -x -c "cp -a input/certs/* /certs && chown 70 certs/* && chmod 600 certs/*"
    volumes:
      - .:/input:ro
      - postgres-certs:/certs

  # Connect to postgresql CLI
  #
  # docker exec -it keycloak-postgres-1 psql --username=keycloak
  #   \dt                     # show tables
  #   select * from pg_user;  # show users
  postgres:
    image: docker.io/postgres:14-alpine
    # uncomment for TLS config
    #command: -c config_file=/configs/postgres.conf
    # uncomment to see all queries
    #command: -c log_statement=all -c log_destination=stderr
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - postgres-certs:/certs:ro
      - ./configs:/configs:ro
    depends_on:
      postgres-init:
       condition: service_completed_successfully

  pgadmin:
    # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
    image: dpage/pgadmin4:8
    user: root
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_SERVER_JSON_FILE=/configs/pgadmin-servers.json
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - ./configs:/configs:ro

volumes:
  postgres-certs:
