# releases
# https://www.docker.elastic.co/r/logstash/logstash-oss

FROM docker.elastic.co/logstash/logstash-oss:8.4.1


# (optional if any)
# add forked versions of the gems
# remove versions that are bundled with the base image
#RUN rm -rf /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-lumberjack-3.1.9/* /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/jls-lumberjack-0.0.26/*
#ADD gems/ /usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/
