# releases
# https://www.docker.elastic.co/r/logstash/logstash-oss

FROM docker.elastic.co/logstash/logstash-oss:8.4.1

# add forked versions of the gems
ADD gems/ /usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/
