subject: cn=server-ca
---
subject: cn=client-ca
---
subject: cn=envoy
issuer: cn=server-ca
sans:
  - DNS:localhost
---
subject: cn=client-sub-ca
issuer: cn=client-ca
ca: true
---
subject: cn=client
issuer: cn=client-ca
revoked: false
---
subject: cn=revoked-client
issuer: cn=client-ca
revoked: true
---
subject: cn=client-under-subca
issuer: cn=client-sub-ca
