resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: tls_certificate_secret
    tls_certificate:
      certificate_chain:
        filename: /home/tsaarni/work/devenvs/envoy/certs/envoy.pem
      private_key:
        filename: /home/tsaarni/work/devenvs/envoy/certs/envoy-key.pem
