resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: validation_context_secret
    validation_context:
      trusted_ca:
        filename: /input/certs/client-ca.pem
      #watched_directory:
      #  path: /home/tsaarni/work/devenvs/envoy/certs
      #crl:
      #  filename: /home/tsaarni/work/devenvs/envoy/certs/client-ca-crl.pem
