resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: validation_context_secret
    validation_context:
      trusted_ca:
        filename: /home/tsaarni/work/devenvs/envoy/certs/client-ca.pem
      crl:
        filename: /home/tsaarni/work/devenvs/envoy/certs/client-ca-crl.pem
