{
 "title": "Envoy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "cgroup",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cgroup_memory_current_bytes{pod=\"envoy-0\", container=\"envoy\"}",
     "legendFormat": "cgroup_memory_current_bytes"
    },
    {
     "expr": "cgroup_memory_peak_bytes{pod=\"envoy-0\", container=\"envoy\"}",
     "legendFormat": "cgroup_memory_peak_bytes"
    },
    {
     "expr": "cgroup_memory_max_bytes{pod=\"envoy-0\", container=\"envoy\"}",
     "legendFormat": "cgroup_memory_max_bytes"
    }
   ]
  },
  {
   "title": "Memory pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(envoy_memory_heap_size-envoy_memory_pageheap_unmapped-envoy_memory_pageheap_free)",
     "legendFormat": "used_memory"
    },
    {
     "expression": "($used_memory/$max_heap_size_bytes)",
     "type": "math"
    },
    { "expression": "100000000", "type": "math" }
   ]
  },
  {
   "title": "TCMalloc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "envoy_memory_allocated{instance=\"http://envoy:9901/memory\"}",
     "legendFormat": "allocated"
    },
    {
     "expr": "envoy_memory_heap_size{instance=\"http://envoy:9901/memory\"}",
     "legendFormat": "heap_size"
    },
    {
     "expr": "envoy_memory_pageheap_unmapped{instance=\"http://envoy:9901/memory\"}",
     "legendFormat": "pageheap_unmapped"
    },
    {
     "expr": "envoy_memory_pageheap_free{instance=\"http://envoy:9901/memory\"}",
     "legendFormat": "pageheap_free"
    },
    {
     "expr": "envoy_memory_total_thread_cache{instance=\"http://envoy:9901/memory\"}",
     "legendFormat": "total_thread_cache"
    },
    {
     "expr": "envoy_memory_total_physical_bytes{instance=\"http://envoy:9901/memory\"}",
     "legendFormat": "total_physical_bytes"
    }
   ]
  },
  {
   "title": "HTTP responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum(increase(envoy_listener_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[$__interval])) > bool 0",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(increase(envoy_listener_http_downstream_rq_xx{envoy_response_code_class=\"2\"}[$__interval])) > bool 0",
     "legendFormat": "2xx"
    },
    {}
   ]
  },
  {
   "title": "Memory unmap ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum(increase(envoy_overload_envoy_overload_actions_shrink_heap_shrink_count[$__interval])) > bool 0",
     "legendFormat": "shrink_count (overload action)"
    },
    {
     "expr": "sum(increase(envoy_tcmalloc_released_by_timer[$__interval])) > bool 0",
     "legendFormat": "released_by_timer (memory allocator manager)"
    },
    {
     "expr": "rate(\n  envoy_memory_pageheap_unmapped[$__interval]\n) ",
     "legendFormat": "unmapped"
    }
   ]
  }
 ]
}