kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        # change port range so that we can bind privileged ports with NodePort
        # this is needed so that we can use default http and https ports when connecting services
        # with clients such as httpie without having to override HTTP header
        # "Host: host1.external.com:31390" with "Host: host1.external.com"
        service-node-port-range: 80-32767
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
