subject: cn=client-ca
key_type: EC
---
subject: cn=server-ca
key_type: EC
---
issuer: cn=client-ca
subject: cn=client
key_type: EC
---
issuer: cn=client-ca
subject: cn=client-rsa
key_type: RSA
---
issuer: cn=client-ca
subject: cn=client-revoked
key_type: EC
revoked: true
---
issuer: cn=server-ca
subject: cn=server
key_type: RSA
sans:
- DNS:logstash-destination
- DNS:localhost
- DNS:rsyslog.127-0-0-1.nip.io
- DNS:httpserver.127-0-0-1.nip.io
---
issuer: cn=server-ca
subject: cn=server-revoked
key_type: EC
revoked: true
sans:
- DNS:logstash-destination
- DNS:localhost
---
issuer: cn=server-ca
subject: cn=rsyslog
sans:
- DNS:localhost
- DNS:rsyslog.127-0-0-1.nip.io
revoked: false
key_type: EC
