# Force rebuild:
#   docker compose build --no-cache

services:

  # Build sssd-build-image image first.
  # The service does not really do anything else, just a placeholder for the image.
  sssd-build-image:
    build: docker/sssd-build-image
    command: /bin/true

  sssd:
    build: docker/sssd
    ports:
      - "2222:22"
    user: "900:900"
    volumes:
      - shared_volume:/usr/local/
    depends_on:
      - sssd-build-image

  openldap:
    build: docker/openldap
    volumes:
      - .:/input:ro

  vscode:
    build: docker/vscode
    ports:
      - "12222:22"
    volumes:
      - .:/workspace:cached
      - /home/tsaarni/work/openssh-portable:/workspace/source/openssh:cached
      - /home/tsaarni/work/sssd:/workspace/source/sssd:cached
      - shared_volume:/usr/local/
    depends_on:
      - sssd-build-image


volumes:
  shared_volume:
