kind: Service
apiVersion: v1
metadata:
  name: contour-authserver
  namespace: projectcontour
spec:
  type: ClusterIP
  ports:
  - port: 19443
    targetPort: 19443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: contour-authserver
  namespace: projectcontour
subsets:
 - addresses:
     - ip: REPLACE_ADDRESS_HERE
   ports:
     - port: 19443
