apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour-authserver
  namespace: projectcontour
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contour-authserver
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contour-authserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour-authserver
subjects:
- kind: ServiceAccount
  name: contour-authserver
  namespace: projectcontour
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contour-authserver
  namespace: projectcontour
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: contour-authserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: contour-authserver
    spec:
      serviceAccountName: contour-authserver
      containers:
      - name: contour-authserver
        image: ghcr.io/projectcontour/contour-authserver:v4
        command:
        - /contour-authserver
        args:
        - oidc
        - --config=/config/authserver-config.yaml
        - --tls-ca-path=/tls/ca.crt
        - --tls-cert-path=/tls/tls.crt
        - --tls-key-path=/tls/tls.key
        ports:
        - name: auth
          containerPort: 9443
          protocol: TCP
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: contour-authserver-cert
      - name: config
        configMap:
          name: contour-authserver-config
---
apiVersion: v1
kind: Service
metadata:
  name: contour-authserver
  namespace: projectcontour
spec:
  ports:
  - name: auth
    protocol: TCP
    port: 19443
    targetPort: 19443
  selector:
    app.kubernetes.io/name: contour-authserver
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour-authserver-config
  namespace: projectcontour
data:
  authserver-config.yaml: |
    address: ":9443"
    issuerURL: "http://keycloak.default.svc.cluster.local:8080/realms/master"
    redirectURL: "https://keycloak.127-0-0-101.nip.io/callback"
    redirectPath: "/callback"
    allowEmptyClientSecret: false
    scopes:
    - openid
    - profile
    - email
    - offline_access
    usernameClaim: "nickname"
    serveTLS: false
    clientID: "contour-authserver"
    clientSecret: "llh6qjqUCY9zcTLbRP5eZcRa08T3ZKyE"
---
apiVersion: projectcontour.io/v1alpha1
kind: ExtensionService
metadata:
  name: contour-authserver
  namespace: projectcontour
spec:
  protocol: h2
  services:
  - name: contour-authserver
    port: 19443
