apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-protected
spec:
  selector:
    matchLabels:
      app: echoserver-protected
  template:
    metadata:
      labels:
        app: echoserver-protected
    spec:
      containers:
      - name: echoserver
        image: ghcr.io/tsaarni/echoserver:latest
        env:
        - name: ENV_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ENV_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENV_POD_IP
          valueFrom:
            fieldRef:
              fieldPath:     status.podIP
        - name: ENV_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ENV_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        ports:
        - name: http-api
          containerPort: 8080
        - name: https-api
          containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-protected
spec:
  ports:
  - name: http
    port: 443
    targetPort: https-api
  selector:
    app: echoserver-protected
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: echoserver-protected
spec:
  virtualhost:
    fqdn: protected.127-0-0-101.nip.io
    tls:
      secretName: ingress
  routes:
    - services:
        - name: echoserver-protected
          port: 443

# http --verify=certs/external-root-ca.pem https://protected.127-0-0-101.nip.io
