apiVersion: v1
kind: Service
metadata:
  name: my-fake-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: http-api
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-fake-service
subsets:
- addresses:
  - ip: 10.244.1.5
  ports:
  - name: http
    port: 3000
    protocol: TCP
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: my-fake-service
spec:
  virtualhost:
    fqdn: my-fake-service.127-0-0-101.nip.io
  routes:
    - services:
        - name: my-fake-service
          port: 80
