kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: mygatewayclass
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    group: projectcontour.io
    kind: ContourDeployment
    namespace: projectcontour
    name: contour
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: mygateway
  namespace: projectcontour
spec:
  gatewayClassName: mygatewayclass
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: contour
spec:
  envoy:
    networkPublishing:
      type: NodePortService
  runtimeSettings:
    envoy:
      logging:
        accessLogFormatString: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(x-iops-job-id)%\" \"%REQ(x-iops-runbook-id)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
