kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: mygatewayclass
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    group: projectcontour.io
    kind: ContourDeployment
    namespace: projectcontour
    name: deployment-with-cert-expiration
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: mygateway
  namespace: projectcontour
spec:
  gatewayClassName: mygatewayclass
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: deployment-with-cert-expiration
spec:
  contour:
    certLifetime: 100
