apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: keycloak
spec:
  virtualhost:
    fqdn: keycloak.127-0-0-101.nip.io
    tls:
      secretName: ingress
  routes:
    - services:
        - name: keycloak
          port: 8080
      # Allow also HTTP to make REST API use easier for dev use
      permitInsecure: true
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.0
          command:
            - /bin/bash
            - -cxe
            - |
              /opt/keycloak/bin/kc.sh import --file /config/keycloak-realm.json
              /opt/keycloak/bin/kc.sh start
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HOSTNAME
              value: "keycloak.127-0-0-101.nip.io"
            - name: KC_HTTP_ENABLED
              value: "true"
          volumeMounts:
            - name: keycloak-config
              mountPath: /config
      volumes:
        - name: keycloak-config
          configMap:
            name: keycloak-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  keycloak-realm.json: |
    {
      "realm": "contour",
      "enabled": true,
      "clients": [
        {
          "clientId": "contour",
          "clientAuthenticatorType": "client-secret",
          "secret": "insecure-client-secret",
          "enabled": true,
          "redirectUris": ["https://protected.127-0-0-101.nip.io/*"],
          "webOrigins": ["*"],
          "publicClient": false,
          "protocol": "openid-connect",
          "attributes": {
            "post.logout.redirect.uris": "https://protected.127-0-0-101.nip.io/*"
          }
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "viewer",
            "description": "Can view content"
          },
          {
            "name": "editor",
            "description": "Can view and edit content"
          }
        ]
      },
      "users": [
        {
          "username": "joe",
          "email": "joe@example.com",
          "firstName": "Joe",
          "lastName": "Joe",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "password"
            }
          ],
          "realmRoles": ["viewer"]
        },
        {
          "username": "jane",
          "email": "jane@example.com",
          "firstName": "Jane",
          "lastName": "Jane",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "password"
            }
          ],
          "realmRoles": ["editor", "viewer"]
        }
      ]
    }
