subject: cn=ca
---
subject: cn=vault
issuer: cn=ca
sans:
- DNS:localhost
- DNS:vault
- DNS:vault-0.vault-internal
- DNS:vault-1.vault-internal
- DNS:vault-2.vault-internal
---
subject: cn=etcd
issuer: cn=ca
sans:
- DNS:etcd
- DNS:etcd0
- DNS:etcd1
- DNS:etcd2
---
subject: cn=client
issuer: cn=ca
