apiVersion: v1
kind: Pod
metadata:
  name: dirwatcher-nonroot

  labels:
    app: dirwatcher-nonroot

spec:
  containers:
    - name: dirwatcher-nonroot

      image: dirwatcher:latest
      imagePullPolicy: Never
      command: ["/bin/sh"]
      args:
        - "-c"
        - "/app/main /secret /secret/password"
      volumeMounts:
        - mountPath: /secret
          name: mysecret
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - all
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true

  securityContext:
    fsGroup: 10000
    #supplementalGroups:
    #  - 0
    # runAsUser: 1234
    # runAsGroup: 5678
    #fsGroupChangePolicy: "OnRootMismatch"

  volumes:
  - name: mysecret
    secret:
      secretName: mysecret
      defaultMode: 0440
      optional: true
