apiVersion: v1
kind: Pod
metadata:
  name: dirwatcher-nonroot

  labels:
    app: dirwatcher-nonroot

spec:
  containers:
    - name: dirwatcher-nonroot

      image: dirwatcher:latest
      imagePullPolicy: Never
      command: ["/app/main"]
      env:
        - name: DEBUG
          value: "false"
      volumeMounts:
        - mountPath: /secret
          name: mysecret
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - all
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
  #serviceAccountName: my-service-account
  securityContext:
    fsGroup: 10000
    #supplementalGroups:
    #  - 0
    # runAsUser: 1234
    # runAsGroup: 5678

  volumes:
  - name: mysecret
    secret:
      secretName: mysecret
      defaultMode: 0440
