tls:
#  envoy-client-certificate:
#    name: envoy-client-cert
#    namespace: projectcontour
#  fallback-certificate:
#    name: fallback-cert
#    namespace: projectcontour
#  minimum-protocol-version: 1.1
