admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
layered_runtime:
  layers:
    - name: root
      disk_layer:
        symlink_root: /home/tsaarni/work/contour-devenv/configs/current
        subdirectory: envoy
