resources:
  - "@type": "type.googleapis.com/envoy.api.v2.auth.Secret"
    tls_certificate:
      certificate_chain:
        filename: /certs/envoy.pem
      private_key:
        filename: /certs/envoy-key.pem
