kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        # change port range so that we can bind privileged ports with NodePort
        # this is needed so that we can use default http and https ports when connecting services
        # with clients such as httpie without having to override HTTP header
        # "Host: host1.external.com:31390" with "Host: host1.external.com"
        service-node-port-range: 80-32767
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "fd61:97d2:3f5a:16e0::1"
  - containerPort: 443
    hostPort: 443
    listenAddress: "fd61:97d2:3f5a:16e0::1"
networking:
  # note:
  # the cluster will not be really IPv6 only since kernel has IPv4 enabled
  # pods will have IPv4 addresses for localhost.
  ipFamily: ipv6
