FROM ubuntu:18.04
RUN apt update && \
    apt install -y build-essential pkg-config automake libsasl2-dev libdb5.3-dev heimdal-multidev libssl-dev libltdl-dev groff-base unixodbc-dev libperl-dev git
COPY files /
