apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  selector:
    app: etcd
  ports:
  - name: client
    port: 2379
    targetPort: 2379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  replicas: 3
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        #image: quay.io/coreos/etcd:v3.3.11
        image: quay.io/coreos/etcd:v3.4.18
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "etcd --data-dir /etcd-data --name ${POD_NAME} --initial-advertise-peer-urls http://${POD_NAME}.etcd:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://${POD_NAME}.etcd:2379 --listen-client-urls http://0.0.0.0:2379 --initial-cluster ${CLUSTER} --debug"
        ports:
        - containerPort: 2379
        - containerPort: 2380
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CLUSTER
            value: etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380
        volumeMounts:
        - name: etcd
          mountPath: /etcd-data
  volumeClaimTemplates:
  - metadata:
      name: etcd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
