apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  selector:
    app: etcd
  ports:
  - name: client
    port: 2379
    targetPort: 2379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  replicas: 3
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        # https://github.com/etcd-io/etcd/releases
        # NOTE: newer images do not have /bin/sh anymore so we cannot use env vars
        image: localhost/etcd:latest
        imagePullPolicy: Never
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "etcd --data-dir /etcd-data --name ${POD_NAME} --initial-advertise-peer-urls http://${POD_NAME}.etcd:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://${POD_NAME}.etcd:2379 --listen-client-urls http://0.0.0.0:2379 --initial-cluster ${CLUSTER} --log-level=debug"
#          - "etcd --data-dir /etcd-data --name ${POD_NAME} --initial-advertise-peer-urls http://${POD_NAME}.etcd:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls https://${POD_NAME}.etcd:2379 --listen-client-urls https://0.0.0.0:2379 --initial-cluster ${CLUSTER} --log-level=debug --client-cert-auth --trusted-ca-file=/certs/ca.pem --cert-file=/certs/etcd.pem --key-file=/certs/etcd-key.pem"
        ports:
        - containerPort: 2379
        - containerPort: 2380
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CLUSTER
            value: etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380
          #- name: ETCD_QUOTA_BACKEND_BYTES
          #  value: "5000000"
        volumeMounts:
        - name: etcd
          mountPath: /etcd-data
        - name: certs
          mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: etcd-certs
            optional: true

  # kubectl delete pvc -l app=etcd
  volumeClaimTemplates:
  - metadata:
      name: etcd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
