apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-client
---
apiVersion: v1
kind: Pod
metadata:
  name: shell
  labels:
    app: shell
spec:
  containers:
    - name: shell
      image: alpine:latest
      command: ["/bin/sh"]
      args:
        - "-c"
        - "apk add --update-cache py3-pip httpie openssl netcat-openbsd && sleep 99999999"
      securityContext:
        privileged: true
      volumeMounts:
        - name: projected
          mountPath: "/projected"
          readOnly: true
  serviceAccountName: vault-client
  volumes:
    - name: projected
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 600
              path: token
              audience: https://my-own-audience

